### ISSUE TITLE
compilation error: duplicate definition of item

### ISSUE THREAD

**Issue by phoenicyan** [varding/wtl-rs#1]
Hi, I wanted to use wtl-rs in designing of a new app, but attempt to compile wtl-rs resulted in errors:
error[E0592]: duplicate definitions with name `item`
    --> pkg\winapi\src\macros.rs:148:13
     |
148  |             pub unsafe fn $variant(&self) -> &$fieldtype {
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |             |
     |             duplicate definitions for `item`
     |             other definition for `item`
     | 
    ::: pkg\winapi\src\commctrl.rs:2496:1
     |
2496 | UNION!(TVINSERTSTRUCTA, itemex, item, item_mut, TV_ITEMA);
     | ---------------------------------------------------------- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0592]: duplicate definitions with name `item_mut`
    --> pkg\winapi\src\macros.rs:152:13
     |
152  |             pub unsafe fn $variantmut(&mut self) -> &mut $fieldtype {
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |             |
     |             duplicate definitions for `item_mut`
     |             other definition for `item_mut`
     | 
    ::: pkg\winapi\src\commctrl.rs:2496:1
     |
2496 | UNION!(TVINSERTSTRUCTA, itemex, item, item_mut, TV_ITEMA);
     | ---------------------------------------------------------- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

What would be the right approach to fix the errors?

Thanks from Arizona!

**Comment by phoenicyan** [comment]
I have fixed this bug, and other bugs that I came across, and published the latest code here: https://github.com/phoenicyan/wtl-rs. It compiles with Rust 1.48. I did not find how to contribute into this repo, so I created new copy.
